
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 14 23:40:59 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 9;
  public static final int RIGHT_BRACKET = 28;
  public static final int INCREMENT = 20;
  public static final int CONST = 47;
  public static final int CHAR = 4;
  public static final int SUBTRACT = 7;
  public static final int NOT_EQUAL = 12;
  public static final int CONTINUE = 43;
  public static final int GREATER = 13;
  public static final int INTERFACE = 34;
  public static final int INT = 2;
  public static final int FOR = 40;
  public static final int LESS = 15;
  public static final int DECREMENT = 21;
  public static final int AND = 17;
  public static final int INT_VALUE = 51;
  public static final int OR = 18;
  public static final int BOOL = 3;
  public static final int COMMA = 23;
  public static final int LEFT_BRACE = 29;
  public static final int ORD = 49;
  public static final int CLASS = 32;
  public static final int SEPARATOR = 22;
  public static final int RIGHT_PARENTHESIS = 26;
  public static final int LESS_EQUAL = 16;
  public static final int MULTIPLY = 8;
  public static final int IF = 37;
  public static final int ASSIGN = 19;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int EQUAL = 11;
  public static final int GREATER_EQUAL = 14;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int PROGRAM = 31;
  public static final int ADD = 6;
  public static final int MODULO = 10;
  public static final int NULL = 5;
  public static final int RIGHT_BRACE = 30;
  public static final int BREAK = 42;
  public static final int VOID = 46;
  public static final int ERROR = 55;
  public static final int BOOL_VALUE = 53;
  public static final int ELSE = 38;
  public static final int READ = 45;
  public static final int ENUM = 36;
  public static final int POINT = 24;
  public static final int CHAR_VALUE = 52;
  public static final int EXTENDS = 33;
  public static final int LEN = 50;
  public static final int CHR = 48;
  public static final int IMPLEMENTS = 35;
  public static final int LEFT_BRACKET = 27;
  public static final int PRINT = 44;
  public static final int LEFT_PARENTHESIS = 25;
  public static final int IDENTIFIER = 54;
}

